version: '3.4'

name: metrodevservices

services:
  ticketera.httpapi.host:
    image: ${DOCKER_REGISTRY-}ticketerahttpapihost
    build:
      context: .
      dockerfile: src/Ticketera.HttpApi.Host/Dockerfile
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pwd0123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "44311:443"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro

  mssql:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SAsasa54
   