version: '3.4'

name: metrodevservices

services:
  ticketera.httpapi.host:
    image: ${DOCKER_REGISTRY-}ticketerahttpapihost
    build:
      context: .
      dockerfile: src/Ticketera.HttpApi.Host/Dockerfile
    depends_on:
      - mssql

  mssql:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SAsasa54

