//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketera {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ticketera.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Purchase Error Email&lt;/title&gt;
        ///    &lt;style&gt;
        ///        /* Estilos generales */
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 0;
        ///        }
        ///
        ///        .container {
        ///            max-width: 500px;
        ///            margin: 0 auto;
        ///            padding: 20px;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string expired_purchase {
            get {
                return ResourceManager.GetString("expired_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;
        ///    &lt;td style=&quot;padding-left: 7%;&quot;&gt;
        ///        &lt;strong&gt;{{infoTicket}}&lt;/strong&gt;
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;padding-left: -40px;&quot;&gt;
        ///        &lt;a href=&quot;{{urlTicket}}&quot;&gt;{{text11}}&lt;/a&gt;
        ///    &lt;/td&gt;
        ///&lt;/tr&gt;
        ///
        ///.
        /// </summary>
        public static string list_tickets {
            get {
                return ResourceManager.GetString("list_tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;style&gt;
        ///    .tableInit {
        ///        width: 100%;
        ///        max-width: 500px;
        ///        text-align: center;
        ///    }
        ///    .invoice-box {
        ///        padding: 25px;
        ///        border: 4px solid #756a6a;
        ///        border-radius: 20px;
        ///        box-shadow: 0 0 10px rgba(68, 65, 65, 0.15);
        ///        font-size: 14px;
        ///        font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;
        ///        color: #555;
        ///    }
        /// 
        ///        .invoice-box table {
        ///            width: 100%;
        ///            line-height: inherit;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string purchase_confirmation {
            get {
                return ResourceManager.GetString("purchase_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Purchase Error Email&lt;/title&gt;
        ///    &lt;style&gt;
        ///        /* Estilos generales */
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 0;
        ///        }
        ///
        ///        .container {
        ///            max-width: 500px;
        ///            margin: 0 auto;
        ///            padding: 20px;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string purchase_error {
            get {
                return ResourceManager.GetString("purchase_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Purchase Pending Email&lt;/title&gt;
        ///    &lt;style&gt;
        ///        /* Estilos generales */
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            background-color: #f4f4f4;
        ///            margin: 0;
        ///            padding: 0;
        ///        }
        ///
        ///        .container {
        ///            max-width: 500px;
        ///            margin: 0 auto;
        ///            padding: 20px;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string purchase_pending {
            get {
                return ResourceManager.GetString("purchase_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;style&gt;
        ///    .tableInit {
        ///        width: 100%;
        ///        max-width: 500px;
        ///        text-align: center;
        ///    }
        ///    .invoice-box {
        ///        padding: 25px;
        ///        border: 4px solid #756a6a;
        ///        border-radius: 20px;
        ///        box-shadow: 0 0 10px rgba(68, 65, 65, 0.15);
        ///        font-size: 14px;
        ///        font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;
        ///        color: #555;
        ///    }
        /// 
        ///        .invoice-box table {
        ///            width: 100%;
        ///            line-height: inherit;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ticket_enable {
            get {
                return ResourceManager.GetString("ticket_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] TixgoCert {
            get {
                object obj = ResourceManager.GetObject("TixgoCert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;style&gt;
        ///    .tableInit {
        ///        width: 100%;
        ///        max-width: 500px;
        ///        text-align: center;
        ///    }
        ///    .invoice-box {
        ///        padding: 25px;
        ///        border: 4px solid #756a6a;
        ///        border-radius: 20px;
        ///        box-shadow: 0 0 10px rgba(68, 65, 65, 0.15);
        ///        font-size: 14px;
        ///        font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;
        ///        color: #555;
        ///    }
        /// 
        ///        .invoice-box table {
        ///            width: 100%;
        ///            line-height: inherit;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string validated_ticket {
            get {
                return ResourceManager.GetString("validated_ticket", resourceCulture);
            }
        }
    }
}
